apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  flb_log_cw: "true"
  filters.conf: |
    [FILTER]
      Name parser
      Match kube.*
      Key_name log
      Parser crio
    [FILTER]
      Name kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      Buffer_Size 0
      Kube_Meta_Cache_TTL 300s
    [FILTER]
      Name rewrite_tag
      Match kube.*
      Rule $kubernetes['labels']['app'] ^myapp$ app.myapp true
    [FILTER]
      Name parser
      Match app.myapp
      Key_name log
      Parser myapp
      Reserve_Data On
    [FILTER]
      Name grep
      Match app.myapp
      Regex path ^/.*$
    [FILTER]
      Name grep
      Match app.myapp
      Exclude path ^/healthcheck$
  output.conf: |
    [OUTPUT]
      Name cloudwatch_logs
      Match kube.*
      region ap-northeast-2
      log_group_name /aws/containerinsights/project-cluster/application
      log_stream_prefix fargate.
      auto_create_group true
    [OUTPUT]
      Name cloudwatch_logs
      Match app.myapp
      region ap-northeast-2
      log_group_name project-myapp
      log_stream_name log
      log_stream_template $kubernetes['pod_id']
      auto_create_group true
  parsers.conf: |
    [PARSER]
      Name crio
      Format Regex
      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>P|F) (?<log>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z
      Time_Keep On
    [PARSER]
      Name myapp
      Format Regex
      Regex ^(?<remote_addr>.*) - - (?<time>.*) (?<method>.*) (?<path>.*) (?<status_code>.*) -$
      Time_Key    time
      Time_Format %d/%m/%Y:%H:%M:%S
      Time_Keep On
