apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: amazon-vpc-lattice
spec:
  controllerName: application-networking.k8s.aws/gateway-api-controller
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: <APP>
  namespace: <NAMESPACE>
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: <APP>
  namespace: <NAMESPACE>
spec:
  parentRefs:
    - name: <APP>
      sectionName: http
      namespace: <NAMESPACE>
  rules:
    - matches:
      - path:
        type: Exact
        value: /healthcheck
      backendRefs:
        - name: <SERVICE>
          kind: Service
          namespace: <NAMESPACE>

---
apiVersion: application-networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: <APP>
  namespace: <NAMESPACE>
spec:
    protocol: HTTP
    protocolVersion: HTTP1
    healthCheck:
      enabled: true
      intervalSeconds: 5
      timeoutSeconds: 1
      healthyThresholdCount: 3
      unhealthyThresholdCount: 2
      path: "/healthcheck"
      port: 8080
      protocol: HTTP
      protocolVersion: HTTP1
      statusMatch: "200"
    targetRef:
      group: ""
      kind: Service
      name: <SERVICE>
      namespace: <NAMESPACE>
---
apiVersion: application-networking.k8s.aws/v1alpha1
kind: AccessLogPolicy
metadata:
  name: <APP>
  namespace: <NAMESPACE>
spec:
  destinationArn: "arn:aws:s3:::my-bucket"
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: <APP>
