regions:
  - global
  - us-east-1
  - us-west-1
  - ap-northeast-2
  - ap-northeast-1

blocklist:
  - 1234567890

bypass-alias-check-accounts:
  - 972209100553
  - 648911607072

accounts:
  972209100553:
    filters:
      IAMUser:
        - "admin"
      IAMUserPolicyAttachment:
        - "admin -> AdministratorAccess"
      IAMUserAccessKey:
        - "admin -> AKIA6EXBNS4EWJBLIW5A"
      IAMSAMLProvider:
        - "arn:aws:iam::972209100553:saml-provider/AWSSSO_pmhonly"
      Route53ResourceRecordSet:
        - "samsungskills1.pmh.codes."
        - "_8339d3d779eb7a2c111a1c330a70323d.samsungskills1.pmh.codes."
      Route53HostedZone:
        - "/hostedzone/Z04137042XYEBMIDBIDHV (samsungskills1.pmh.codes.)"
      IAMRole:
        - "admin"
        - "SamsungCloudMgmtPlatform_Linked_Role"
        - "SamsungCloudOpsPlatform_Linked_Role"
        - type: regex
          value: "AWSServiceRoleFor.*"
      IAMRolePolicyAttachment:
        - "admin -> AdministratorAccess"
        - "SamsungCloudMgmtPlatform_Linked_Role -> AWSOrganizationsReadOnlyAccess"
        - "SamsungCloudMgmtPlatform_Linked_Role -> ReadOnlyAccess"
        - "SamsungCloudMgmtPlatform_Linked_Role -> Billing"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonDynamoDBReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonEC2ReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonRDSReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonS3ReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonVPCReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AWSOrganizationsReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> CloudWatchLogsReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> IAMFullAccess"
      CloudTrailTrail:
        - "mytrail"
      CloudFormationStack:
        - "StackSet-SamsungCloudOpsPlatformRoleStackSet-9962d4f1-8c32-488b-81bb-9ffd001720b0"
        - "StackSet-ScmpSecurityAuditorStackSet-faf696dd-fba0-4a63-adf5-3c7e67abc912"
        - "StackSet-SamsungCloudMgmtPlatformStackSet-d7e04c54-5e4a-4ac8-a509-fe2d1e871373"
        - "StackSet-SamsungCloudOpsPlatformStackSet-3f9ed7f2-4e90-4486-ad27-56984de94506"
      ACMCertificate:
        - "arn:aws:acm:us-east-1:972209100553:certificate/6ca5d699-c302-4349-8a87-38160a5b0b02"
      KMSKey:
        - "346c982d-b5f6-4574-bf29-458458ec3d31"
  648911607072:
    filters:
      IAMUser:
        - "admin"
      IAMUserPolicyAttachment:
        - "admin -> AdministratorAccess"
      IAMUserAccessKey:
        - "admin -> AKIAZOFRFKUQGG4EU5OP"
      IAMSAMLProvider:
        - "arn:aws:iam::648911607072:saml-provider/AWSSSO_93b584ed1d22a1c5_DO_NOT_DELETE"
        - "arn:aws:iam::648911607072:saml-provider/AWSSSO_pmhonly"
      Route53ResourceRecordSet:
        - "samsungskills2.pmh.codes."
        - "_a6d0d215e3fb85c4d5d2372846f01f34.samsungskills2.pmh.codes."
      Route53HostedZone:
        - "/hostedzone/Z093302115ZHXKOFEFJ2Q (samsungskills2.pmh.codes.)"
      IAMPolicy:
        - "arn:aws:iam::648911607072:policy/SCOP_IAM_POLICY"
        - "arn:aws:iam::648911607072:policy/SCOP_PRD_INFRAMANAGEMENT_PERMISSION_BOUNDARY_PL"
        - "arn:aws:iam::648911607072:policy/SCOP_DYNAMO_WRITER"
        - "arn:aws:iam::648911607072:policy/SCOP_DYNAMO_READER"
        - "arn:aws:iam::648911607072:policy/SCOP_S3_WRITER"
        - "arn:aws:iam::648911607072:policy/SCOP_S3_READER"
        - "arn:aws:iam::648911607072:policy/SamsungCloudOpsPlatform_Linked_Policy_20230918"
      IAMRole:
        - "admin"
        - "RBAC_SCOP_DYNMRD"
        - "RBAC_SCOP_DYNMWT"
        - "RBAC_SCOP_MEMBER"
        - "RBAC_SCOP_PL"
        - "RBAC_SCOP_S3READ"
        - "RBAC_SCOP_S3WRIT"
        - "SamsungCloudMgmtPlatform_Linked_Role"
        - "SamsungCloudOpsPlatform_Linked_Role"
        - "SamsungCloudOpsPlatform_Linked_Role_20230918"
        - "scmp_security_auditor"
        - "stacksets-exec-d1373500c74b3a738a04f178177902a4"
        - type: regex
          value: "AWSServiceRoleFor.*"
      IAMRolePolicyAttachment:
        - "admin -> AdministratorAccess"
        - "RBAC_SCOP_DYNMRD -> SCOP_DYNAMO_READER"
        - "RBAC_SCOP_DYNMWT -> SCOP_DYNAMO_WRITER"
        - "RBAC_SCOP_MEMBER -> AdministratorAccess"
        - "RBAC_SCOP_PL -> AdministratorAccess"
        - "RBAC_SCOP_S3READ -> SCOP_S3_READER"
        - "RBAC_SCOP_S3WRIT -> SCOP_S3_WRITER"
        - "SamsungCloudMgmtPlatform_Linked_Role -> AWSOrganizationsReadOnlyAccess"
        - "SamsungCloudMgmtPlatform_Linked_Role -> ReadOnlyAccess"
        - "SamsungCloudMgmtPlatform_Linked_Role -> Billing"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonDynamoDBReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonEC2ReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonRDSReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonS3ReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AmazonVPCReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> AWSOrganizationsReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> CloudWatchLogsReadOnlyAccess"
        - "SamsungCloudOpsPlatform_Linked_Role -> IAMFullAccess"
        - "SamsungCloudOpsPlatform_Linked_Role_20230918 -> SamsungCloudOpsPlatform_Linked_Policy_20230918"
        - "scmp_security_auditor -> ReadOnlyAccess"
        - "scmp_security_auditor -> AWSSupportAccess"
        - "stacksets-exec-d1373500c74b3a738a04f178177902a4 -> AdministratorAccess"
      IAMRolePolicy:
        - "SamsungCloudOpsPlatform_Linked_Role -> COP-ASSET-POLICY"
      CloudTrailTrail:
        - "mytrail"
      CloudFormationStack:
        - "StackSet-SamsungCloudOpsPlatformRoleStackSet-9962d4f1-8c32-488b-81bb-9ffd001720b0"
        - "StackSet-ScmpSecurityAuditorStackSet-faf696dd-fba0-4a63-adf5-3c7e67abc912"
        - "StackSet-SamsungCloudMgmtPlatformStackSet-d7e04c54-5e4a-4ac8-a509-fe2d1e871373"
        - "StackSet-SamsungCloudOpsPlatformStackSet-3f9ed7f2-4e90-4486-ad27-56984de94506"
      ACMCertificate:
        - "arn:aws:acm:us-east-1:648911607072:certificate/55aa50fd-1bc8-4538-9284-df2a6245d372"
      KMSKey:
        - "91a8e47e-5cbf-43e5-89e0-0d2207b25cb7"

settings:
  EC2Image:
    IncludeDisabled: true
    IncludeDeprecated: true
    DisableDeregistrationProtection: true
  EC2Instance:
    DisableStopProtection: true
    DisableDeletionProtection: true
  RDSInstance:
    DisableDeletionProtection: true
  CloudFormationStack:
    DisableDeletionProtection: true
  DynamoDBTable:
    DisableDeletionProtection: true
  CognitoUserPool:
    DisableDeletionProtection: true
  DocDBCluster:
    DisableDeletionProtection: true
  DSQLCluster:
    DisableDeletionProtection: true
  EKSCluster:
    DisableDeletionProtection: true
  ELBv2:
    DisableDeletionProtection: true
  NeptuneCluster:
    DisableDeletionProtection: true
  NeptuneGraph:
    DisableDeletionProtection: true
  NeptuneInstance:
    DisableDeletionProtection: true
  PinpointPhoneNumber:
    DisableDeletionProtection: true
  QLDBLedger:
    DisableDeletionProtection: true

resource-types:
  excludes:
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service
    - ElasticTranscoderPipeline
    - ElasticTranscoderPreset
    - QLDBLedger
